[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Cache-Control = "public, max-age=0"
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Cache-Control = "public, max-age=0"
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"

# Redirect deep links to the index for the React Router to handle
[[redirects]]
  from = "/s/*"
  to = "/index.html"
  status = 200
  force = true