# Redirect configuration for .well-known directory
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json" # or "text/plain"

# Redirect for deep linking
[[redirects]]
  from = "/s/*"
  to = "myapp://s/:splat"
  status = 302
  force = true