## Temporary: deep link pattern. Once Firebase links subdomain is live, remove this.
[[redirects]]
  from = "/s/*"
  to = "lomaevents://s/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/support"
  to = "/support.html"
  status = 200
  force = true